#
version: '2'
#
services:
  #
  mysql:
    image: mysql:5.7
    ports:
      - "127.0.0.1:3306:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'secret'
      TIMEZONE: 'Asia/Tbilisi'
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/mysqld.cnf:/etc/mysql/mysql.conf.d/mysqld.cnf
  #
  php5-fpm:
    build: ./PHP/php5-fpm
    restart: always
    volumes:
      - /Users/lotuashvili/Sites:/www
  php7-fpm:
    build: ./PHP/php7-fpm
    restart: always
    volumes:
      - /Users/lotuashvili/Sites:/www
  #
  nginx:
    image: nginx:latest
    ports:
      - '127.0.0.1:80:80'
    restart: always
    volumes:
      - ./Nginx/sites:/etc/nginx/sites
      - ./Nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./Nginx/nginx-php-common.conf:/etc/nginx/nginx-php-common.conf
      - /Users/lotuashvili/Sites:/www
  #
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - ./redis:/var/lib/redis
    restart: always
    command: >
      --requirepass secret
